# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyconfigs" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/thousandbrainsproject/lazyconfigs/releases/download/v#{version}/lazyconfigs_#{version}_darwin_amd64.tar.gz"
      sha256 "b4ee81c24fa22e31fe98bbd7dcd4bbdce8f7f79eb11ccfa1b445a477f7294028"
    end
    on_arm do
      url "https://github.com/thousandbrainsproject/lazyconfigs/releases/download/v#{version}/lazyconfigs_#{version}_darwin_arm64.tar.gz"
      sha256 "ef0732d58e5dc5f40a05f34f5c6c7da851131c0beae17ac4093e59b3bd524ad8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thousandbrainsproject/lazyconfigs/releases/download/v#{version}/lazyconfigs_#{version}_linux_amd64.tar.gz"
      sha256 "c414c3e40a0441f21bb85195e72832f944bc6f8c9332a142d72fc3eeb101519e"
    end
    on_arm do
      url "https://github.com/thousandbrainsproject/lazyconfigs/releases/download/v#{version}/lazyconfigs_#{version}_linux_arm64.tar.gz"
      sha256 "7c85a018e8fbd91a43d59f43daa89337807995e76e44208fd63ab0e0a3815b0b"
    end
  end

  name "lazyconfigs"
  desc "TUI for browsing and editing Hydra/YAML configs"
  homepage "https://github.com/thousandbrainsproject/lazyconfigs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyconfigs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyconfigs"]
    end
  end

  # No zap stanza required

end
